package.json
yarn.lock

- Add `standard-version` part of the `webpack-defaults` tool set for changelog generation

chore(release): add standard-version

---

package.json

Without breaking changes
- Fixes https://github.com/webpack-contrib/source-map-loader/issues/54

chore: update `dependencies`

---

index.js
package-lock.json
package.json

chore(package): remove unused `source-map` dependency (`dependencies`)

---

package-lock.json
package.json
src/index.js
test/index.test.js

refactor: code
fixes #93 
No
No

refactor: code

---

package-lock.json
package.json
src/index.js
src/utils/flatten.js
test/__snapshots__/loader.test.js.snap
test/fixtures/indexed-sourcemap/file.js
test/fixtures/indexed-sourcemap/file.js.map
test/fixtures/indexed-sourcemap/nested1.js
test/fixtures/indexed-sourcemap/nested2.js
test/helpers/normalizeMap.js
test/loader.test.js

feat: indexed-sourcemap

---

README.md
src/index.js
src/utils.js
test/__snapshots__/loader.test.js.snap
test/loader.test.js

docs: ignore example

---

.gitignore
src/utils.js
test/__snapshots__/loader.test.js.snap
test/fixtures/server-relative-url-path.js
test/fixtures/unresolved-server-relative-url-path.js
test/helpers/getWarnings.js
test/helpers/normalizeErrors.js
test/loader.test.js

Resolve server-relative url

---

README.md
src/index.js
src/options.json
test/__snapshots__/filterSourceMappingUrl.test.js.snap
test/__snapshots__/validate-options.test.js.snap
test/filterSourceMappingUrl.test.js
test/validate-options.test.js

Filter source mapping url

---

README.md

- Add link to `ignoreWarnings` option
- Relates to c0a7a80

Add link to `ignoreWarnings` option

---

package-lock.json
package.json
src/utils.js
test/__snapshots__/loader.test.js.snap
test/fixtures/{percent}.js
test/fixtures/{percent}.js.map
test/loader.test.js

Fix: parse percent-encoding url

---

package-lock.json
package.json
src/utils.js
test/loader.test.js

fix perf due https://github.com/7rulnik/source-map-js
Hope no
No

perf: switch on `source-map-js`

---

.github/workflows/nodejs.yml

chore: migrate to `setup-node/v2`

---

babel.config.js
package-lock.json
package.json

fix node.js version I missed it
No
No

refactor: fix node.js version

---

commitlint.config.js

Disable commit message length check

chore: disable commit msg length check

---

README.md

chore: add installation commands

---

.github/workflows/cancel.yml

update github workflow security
No
No

ci: update github workflow security

---

.github/workflows/nodejs.yml
test/__snapshots__/loader.test.js.snap
test/loader.test.js

ci: add node v19

---

.github/workflows/nodejs.yml
test/loader.test.js

ci: add node v20

---

package-lock.json
package.json
src/parse-data-url.js

fixes https://github.com/webpack-contrib/source-map-loader/pull/226
fixes https://github.com/webpack-contrib/source-map-loader/issues/225
No
We can't use built-in `atob` because we want to be error recovery in some cases

fix: avoid deprecation message of `abab` package

---

README.md

docs: fix outdated broken links

---

.github/workflows/nodejs.yml
package-lock.json

ci: add node v24
