index.js
For now, baseRegex mismatch empty space after <url> which lead to 'Cannot find
SourceMap' problem. 
e.g.  map file name of bootstrap.css ( `/*# sourceMappingURL=bootstrap.css.map */` ) will be resolved to bootstrap.css.map<***space***>
=> Bugfix: fix regex mismatching empty space after sourceMappingURL issue.

index.js
There is an incorrect 'undefined' string in the css file after processing by
source-map-loader.
It's caused by the line 
```javascript
callback(null, input.replace(match[0], match[2]), map);
```
There are two kinds of comment format `regex1` and `regex2`. `regex1` only have one capture group so `match[2]` will be `undefined`. So maybe just replace by empty would be OK?
=> Fix: fix the 'undefined' string in the css file issue.

README.md
Updates README.md to adhere to webpack v2 loader updates. [webpack/webpack issue #3195](https://github.com/webpack/webpack/issues/3195)
=> Update readme to fit webpack v2

README.md
Most people will probably notice this and fix it, but here's a PR if you didn't realise this typo was on there.
=> Fix module name typo

index.js, test/fixtures/charset-inline-source-map.js, test/index.test.js
Hello, it seems that if a charset is specified in an inline source maps the loader does not detect the base64 and triggers a warning.
This PR add the support for the charset by changing a bit the regular exprssion regexDataUrl.
=> Charset in inline-source-map support

index.js, test/fixtures/multi-source-map.js, test/index.test.js
**What kind of change does this PR introduce?**
bugfix
**Did you add tests for your changes?**
Yes.
**Summary**
There is a library bundled by webpack with `style-loader`. A consumer tries to load it through webpack with `source-map-loader`, but it fails to build.
The root cause is `source-map-loader` incorrectly thinks the string literal `"\n/*# sourceMappingURL=data:application/json;base64,"` is a directive for source map, it tries to find the source map here(while the actual source map directive is in the end of file), and fails.
Per source map spec, the directive should appear at the last line of js file. Thus it makes sense to use last match as the one we read source map from.
**Does this PR introduce a breaking change?**
No.
**Other information**
Relates to: …
=> Load source map only from last directive

index.js, test/fixtures/multi-source-map.js, test/index.test.js
This PR is to fix some cases for PR #31 
In minified artifacts of `style-loader`, there is no space in js file, which couldn't be handled by the regex. It is fixed in this PR, and test cases updated accordingly.
=> fix: Regex does not work for minified artifact of style-loader

README.md
Feedback is welcome on the copy to confirm it is accurate.
=> docs(README): add details on usage and purpose

README.md
In my recent README.md, somehow I got the `git diff` newline **+** signs into the copy. 
https://github.com/webpack-contrib/source-map-loader/commit/5501fe3873b74ae6d1cce4583de53b83ee146277
I must have made a silly copy/paste error but fixed it in this PR. Sorry!
=> Remove plus signs from copy.

index.js, test/fixtures/invalid-inline-source-map.js, test/fixtures/invalid-inline-source-map2.js, test/index.test.js
- Fixes #38
> edited by @michael-ciniawsky (Formatting)
=> fix: handle exception on loading invalid `base64` source maps

README.md
`s/souce/source/`
Small typo I caught while reading the documentation.
=> docs(README): Typo fix

index.js, test/fixtures/invalid-source-map.js, test/fixtures/invalid-source-map.map, test/index.test.js
Added a try catch that's pretty much the same as the base64 fix.
=> fix: Handle exception on loading invalid source maps (#65)

index.js, test/fixtures/.gitignore, test/fixtures/absolute-sourceRoot-source-map.js, test/fixtures/absolute-sourceRoot-source-map.txt, test/fixtures/data/relative-sourceRoot-source-map.txt, test/fixtures/relative-sourceRoot-source-map.js, test/fixtures/relative-sourceRoot-source-map.map, test/index.test.js
`source-map-loader` doesn't correctly handle sourcemaps with root-relative `sourceRoot` properties in sourcemaps.
Consider the following example sourcemap:
```JSON
{
"version": 3,
"file": "my-file.js",
"sourceRoot": "/code/my-project/src/",
"sources": [
"my-file.ts"
],
"names": [],
"mappings": "AAAA, ..."
}
```
`source-map-loader` will resolve each of the files referenced in `sources` to be under `sourceRoot` [here](https://github.com/webpack-contrib/source-map-loader/blob/master/index.js#L67-L68) (so in this example, the path becomes `/code/my-project/src//my-file.ts`), and then it will attempt to resolve each of the paths it constructed using `loaderUtils.urlToRequest`. As per the [documentation of `urlToRequest`](https://github.com/webpack/loader-utils#urltorequest), the `root` …
=> fix(index): source maps with root-relative paths

package-lock.json, package.json, src/index.js, src/utils.js, test/__snapshots__/loader.test.js.snap, test/fixtures/charset-inline-source-map.txt, test/fixtures/file-source-map-windows.js, test/fixtures/file-source-map.js, test/fixtures/http-source-map.js, test/fixtures/indexed-sourcemap/file.js, test/fixtures/indexed-sourcemap/file.js.map, test/helpers/getCompiler.js, test/helpers/normalizeMap.js, test/loader.test.js
Fixes #29 
Fixes #77 
Fixes #51 
No
No
=> Feat absolute path for sources

src/index.js, src/utils.js, test/__snapshots__/loader.test.js.snap, test/__snapshots__/sourceMapperRegexp.test.js.snap, test/fixtures/normal-file2.js, test/loader.test.js, test/sourceMapperRegexp.test.js
=> fix: issue 55

src/index.js, src/utils.js
Use loaderContext fs
Fixes #2 
No
No
=> feat: use loaderContext fs

test/__snapshots__/validate-options.test.js.snap, test/validate-options.test.js
=> test: validate options

.gitignore, src/utils.js, test/__snapshots__/loader.test.js.snap, test/fixtures/indexed-sourcemap/file2.js, test/fixtures/indexed-sourcemap/file2.js.map, test/loader.test.js
=> test: coverage

README.md
There's no link with id `url`. It caused the failure of CI on webpack.js.org https://travis-ci.org/github/webpack/webpack.js.org/jobs/722070578#L2932
=> fix: update anchor

README.md
- Use `ignoreWarnings` as `stats.warningsFilter` is deprecated
- See https://github.com/webpack/webpack.js.org/issues/3995
=> Use `ignoreWarnings` as `stats.warningsFilter` is deprecated

README.md
- [  ] **bugfix**
- [  ] new **feature**
- [  ] **code refactor**
- [  ] **test update** 
- [  ] **typo fix**
- [ x] **metadata update**
The link `https://webpack.js.org/configuration/#options:~:text=ignoreWarnings` was added in https://github.com/webpack-contrib/source-map-loader/pull/129, I think the author used it as a workaround because the URL should be used here is currently blocked by this pull request https://github.com/webpack/webpack.js.org/pull/4076.
Now `options:~:text=ignoreWarnings` was recognized as ID (which I believe is a bug as `:~:text=ignoreWarnings` is a [text fragment](https://wicg.github.io/scroll-to-text-fragment/#syntax), but I'm not sure if it'll be a bug in [hyperlink](https://github.com/Munter/hyperlink) or somewhere else) and webpack.js.org …
=> docs: fix ci for webpack.js.org

src/index.js, test/__snapshots__/loader.test.js.snap, test/fixtures/null-in-sources-content.js, test/fixtures/null-in-sources-content.js.map, test/fixtures/null-in-sources-content.txt, test/loader.test.js
#147 
If you will fix it on your own, feel free to use any from this PR and close it
=> Fix null source content ignoring on processing source map

test/__snapshots__/filterSourceMappingUrl.test.js.snap, test/__snapshots__/loader.test.js.snap, test/filterSourceMappingUrl.test.js, test/helpers/testLoader.js, test/loader.test.js
use `code` instead `css`
No
No
=> test: refactor

.github/workflows/nodejs.yml, babel.config.js, package-lock.json, package.json
Support `Node.js` v10 dropped
Support `Node.js` v10 dropped
No
=> refactor: Node.js v10 dropped

.github/workflows/nodejs.yml, babel.config.js, package-lock.json, package.json
Remove node v12 since it has reached EOL
=> feat: drop node v12
